name: update_members

on:
  schedule:
    - cron: '18 10 * * *'
  workflow_dispatch:

jobs:
  update_members:

    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
    - name: Update members.tsv
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pip install beautifulsoup4
        pip install lxml
        python elect_com_mon.py
        bash push.sh